name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # if requirements.txt exists, use it; otherwise install the explicit set you used locally
          if [ -f module_4/requirements.txt ]; then
            python -m pip install -r module_4/requirements.txt
          else
            python -m pip install "Flask>=2.2,<3" "psycopg[binary]>=3.1,<4" "beautifulsoup4>=4,<5" "lxml>=5,<6" "pytest>=8,<9" "pytest-cov>=5,<6" "Sphinx>=7,<8" "sphinx-rtd-theme>=2,<3"
          fi

      - name: Run tests with coverage
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
            mkdir -p module_4
            pytest | tee module_4/coverage_summary.txt

      - name: Upload coverage summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: module_4/coverage_summary.txt