name: tests

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r module_4/requirements.txt

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          mkdir -p module_4
          pytest | tee module_4/coverage_summary.txt

      - name: Upload coverage summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: module_4/coverage_summary.txt